[theme]
primaryColor = "#ce7e00"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#2e3026"
textColor = "#FFFFFF"
font = "monospace"
base = "dark"

[client]
toolbarMode = "minimal"

[server]
enableStaticServing = true
