[theme]
primaryColor = "#ce7e00"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "monospace"
base = "dark"

[client]
toolbarMode = "minimal"

[server]
enableStaticServing = true
